# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(100, 100, 131, 51))
        self.btn.setObjectName("btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.btn.clicked.connect(self.show_dialog)

    def show_dialog(self):
        ''''''
        dialog = QMessageBox(MainWindow)
        dialog.setText('Alert from PyQT5!')
        dialog.setWindowTitle('Access Denied:')
        dialog.setIcon(QMessageBox.Critical) # [Critical, Warning, Information, Question]
        dialog.setInformativeText('You can\'t make any change to this file.')
        dialog.setDetailedText('Please show the guide book or contact the admin.')

        dialog.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel|QMessageBox.Retry)
        dialog.buttonClicked.connect(self.dialog_box)

        dialog.exec_()

    def dialog_box(self, dialog_btn):
        print(dialog_btn.text())
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn.setText(_translate("MainWindow", "Show Dialog Box"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
