# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 472)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.my_img = QtWidgets.QLabel(self.centralwidget)
        self.my_img.setGeometry(QtCore.QRect(16, 16, 461, 341))
        self.my_img.setText("")
        self.my_img.setPixmap(QtGui.QPixmap("../../../../../../../../../home/ehp/Images/pix/IMG00880-20110619-2157.jpg"))
        self.my_img.setScaledContents(True)
        self.my_img.setObjectName("my_img")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(60, 374, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(308, 374, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn1.clicked.connect(self.show_img1)
        self.btn2.clicked.connect(self.show_img2)

    def show_img1(self):
        self.my_img.setPixmap(QtGui.QPixmap("../../../../../../../../../home/ehp/Images/pix/IMG00880-20110619-2157.jpg"))

    def show_img2(self):
        self.my_img.setPixmap(QtGui.QPixmap("../../../../../../../../../home/ehp/Images/pix/IMG00663-20110312-2041.jpg"))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn1.setText(_translate("MainWindow", "IM1"))
        self.btn2.setText(_translate("MainWindow", "IM2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
